// lib/products.js

let products = [
  {
    id: '1',
    name: 'Tarte Fraise 650g',
    description: 'Délicieuse tarte aux fraises fraîches avec une pâte croustillante.',
    price: 10.00, // Prix vendant
    cost: 6.50,    // Prix coutant
    image: '/images/tarte_fraise_650g.png',
  },
  {
    id: '2',
    name: 'Tarte Sucre à la Crème 600g',
    description: 'Tarte crémeuse au sucre à la crème avec une pâte sucrée.',
    price: 10.00,
    cost: 6.50,
    image: '/images/tarte_sucre_a_la_creme_600g.png',
  },
  {
    id: '3',
    name: 'Tarte Pomme 650g',
    description: 'Tarte classique aux pommes avec une touche de cannelle.',
    price: 10.00,
    cost: 6.50,
    image: '/images/tarte_pomme_650g.png',
  },
  {
    id: '4',
    name: 'Tarte Fraise et Rhubarbe',
    description: 'Mélange rafraîchissant de fraises et de rhubarbe dans une tarte gourmande.',
    price: 10.00,
    cost: 6.50,
    image: '/images/tarte_fraise_rhubarbe.png',
  },
  {
    id: '5',
    name: 'Croustade aux Pommes 650g',
    description: 'Croustade aux pommes caramélisées avec une garniture croustillante.',
    price: 10.00,
    cost: 6.50,
    image: '/images/croustade_pommes_650g.png',
  },
  {
    id: '6',
    name: 'Tarte 4 Fruits 650g',
    description: 'Mélange de quatre fruits dans une pâte feuilletée maison.',
    price: 10.00,
    cost: 6.50,
    image: '/images/tarte_4_fruits_650g.png',
  },
  {
    id: '7',
    name: 'Tarte Pomme et Sucre 650g',
    description: 'Tarte aux pommes caramélisées avec une touche de sucre.',
    price: 10.00,
    cost: 6.50,
    image: '/images/tarte_pomme_sucre_650g.png',
  },
  {
    id: '8',
    name: 'Pan Pouding Chômeur 500g',
    description: 'Dessert classique québécois avec un sirop sucré au caramel.',
    price: 9.00,
    cost: 5.75,
    image: '/images/pan_pouding_chomeur_500g.png',
  },
  {
    id: '9',
    name: 'Tartes Framboise 650g',
    description: 'Tarte aux framboises fraîches avec une pâte dorée.',
    price: 11.00,
    cost: 7.75,
    image: '/images/tartes_framboise_650g.png',
  },
  {
    id: '10',
    name: 'Tarte Bleuet 650g',
    description: 'Tarte aux bleuets sauvages dans une pâte légère.',
    price: 11.00,
    cost: 7.75,
    image: '/images/tarte_bleuet_650g.png',
  },
  {
    id: '11',
    name: 'Pâté à poulet',
    description: 'Pâté rempli de poulet tendre et de légumes frais.',
    price: 12.00,
    cost: 8.75,
    image: '/images/pate_poulet.png',
  },
  {
    id: '12',
    name: 'Pâté à viande',
    description: 'Pâté savoureux à base de viande hachée et d\'épices.',
    price: 12.00,
    cost: 8.75,
    image: '/images/pate_viande.png',
  },
  {
    id: '13',
    name: 'Tarte Sirop d\'érable 600g',
    description: 'Tarte traditionnelle au sirop d\'érable pur.',
    price: 12.00,
    cost: 8.75,
    image: '/images/tarte_sirop_erable_600g.png',
  },
  {
    id: '14',
    name: 'Boîte Mélanger (1 pâté viande, 1 poulet, 1 tarte au sucre, 1 pomme, 1 4fruits, 1 sirop)',
    description: 'Un assortiment de nos meilleurs produits pour une dégustation complète.',
    price: 60.00,
    cost: 45.00,
    image: '/images/boite_melanger_1.png',
  },
  {
    id: '15',
    name: 'Boîte Mélanger (2 pâté viande, 2 poulet, 1 tarte au sucre, 1 pomme)',
    description: 'Double assortiment pour plus de gourmandise.',
    price: 60.00,
    cost: 47.00,
    image: '/images/boite_melanger_2.png',
  },
];

export { products };